### ISSUE TITLE
关于将冷 observable 转化成热的部分的一点疑惑

### ISSUE THREAD

**Issue by Raoul1996** [RxJS-CN/rxjs5-ultimate-cn#5]

**Comment by Raoul1996** [comment]
```javascript
let publisher$ = Rx.Observable
.interval(1000)
.take(5)
.publish();


publisher$.subscribe(
  data => console.log('subscriber from first minute',data),
  err => console.log(err),
  () => console.log('completed')
)

setTimeout(() => {
    publisher$.subscribe(
        data => console.log('subscriber from 2nd minute', data),
        err => console.log(err),
        () => console.log('completed')
    )
}, 3000)


publisher$.connect();

```

这部分讲到前者会输出 `0` 到 `4`，后者会输出 `3`，`4`。

但是在学习的时候，发现后者多输出了一个 `2`。

通过打印时间戳进行查看：

```javascript
import {Observable} from 'rxjs'

let publisher$ = Observable
    .interval(1000)
    .take(5)
    .publish();

console.log('timestamp: ', Date.now());

publisher$.subscribe(
    data => console.log('subscriber1 | timestamp: ', Date.now(), ' | ', data),
    err => console.log(err),
    () => console.log('completed')
);

setTimeout(() => {
    publisher$.subscribe(
        data => console.log('subscriber2 | timestamp: ', Date.now(), ' | ', data),
        err => console.log(err),
        () => console.log('completed')
    )
}, 3000);


publisher$.connect();

```
发现 subscribe 的时候耗时比较长。

id | timestamp     |  val
---|----------|-----------------
 null | timestamp:  1536067125682 | null
subscriber1 | timestamp:  1536067126727  |  0
subscriber1 | timestamp:  1536067127730  |  1
subscriber1 | timestamp:  1536067128732  |  2
subscriber2 | timestamp:  1536067128733  |  2
subscriber1 | timestamp:  1536067129736  |  3
subscriber2 | timestamp:  1536067129738  |  3
subscriber1 | timestamp:  1536067130743  |  4
subscriber2 | timestamp:  1536067130744  |  4

**Comment by Raoul1996** [comment]
"rxjs": "^5.5.12",

**Comment by SangKa** [comment]
冷转热的本质就是多播，关于多播可以看[这篇文章](https://zhuanlan.zhihu.com/p/33225623)，强烈推荐。
原作者写这个时候，还没有 RxJS 5.5 版本，所以会存在某些不一致性的。本仓库近日将同步成最新 (#6 )，届时可以再用 RxJS 6 来尝试。
